id: bcc556d9-fce6-49e7-bc65-e5049000a4f6
name: configure-monitoring
description: Configure monitoring wiring (promtail → Loki, Prometheus target registration)
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to configure monitoring for
jobs:
  - name: configure
    description: Discover hub, lookup VM, configure promtail and register with Prometheus
    steps:
      - name: auth
        description: Authenticate with Proxmox
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: discover-hub
        description: Validate observability stack on hancock
        task:
          type: model_method
          modelIdOrName: hancockMonitoring
          methodName: discover
        dependsOn: []
        weight: 0
      - name: lookup-vm
        description: Lookup target VM in fleet
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: configure-promtail
        description: Configure promtail on the VM to push logs to Loki
        task:
          type: model_method
          modelIdOrName: monitoringAgent
          methodName: configure
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup-vm
            condition:
              type: succeeded
          - step: discover-hub
            condition:
              type: succeeded
        weight: 0
      - name: register-target
        description: Register VM as a Prometheus scrape target on hancock
        task:
          type: model_method
          modelIdOrName: hancockMonitoring
          methodName: register
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup-vm
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
