id: bac98235-a359-4e2d-bf59-bba3139f3f76
name: setup-monitoring
description: Full monitoring setup — install agents + configure wiring + register with Prometheus
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to set up monitoring on
jobs:
  - name: setup
    description: Auth + discover hub, lookup VM, install agents, configure promtail + register target
    steps:
      - name: auth
        description: Authenticate with Proxmox
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: discover-hub
        description: Validate observability stack on hancock
        task:
          type: model_method
          modelIdOrName: hancockMonitoring
          methodName: discover
        dependsOn: []
        weight: 0
      - name: lookup-vm
        description: Lookup target VM in fleet
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: install-agents
        description: Install node-exporter and promtail on the VM
        task:
          type: model_method
          modelIdOrName: monitoringAgent
          methodName: install
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup-vm
            condition:
              type: succeeded
        weight: 0
      - name: configure-promtail
        description: Configure promtail on the VM to push logs to Loki
        task:
          type: model_method
          modelIdOrName: monitoringAgent
          methodName: configure
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: install-agents
            condition:
              type: succeeded
          - step: discover-hub
            condition:
              type: succeeded
        weight: 0
      - name: register-target
        description: Register VM as a Prometheus scrape target on hancock
        task:
          type: model_method
          modelIdOrName: hancockMonitoring
          methodName: register
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: install-agents
            condition:
              type: succeeded
          - step: discover-hub
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
