id: 31fbed74-d3be-431c-b924-864febc11e54
name: setup-game-metrics
description: One-time setup — enable node-exporter textfile collector on a game server VM
inputs:
  vmName:
    type: string
    required: true
    description: Name of the VM to enable textfile collector on
jobs:
  - name: setup
    description: Auth, lookup VM, enable textfile collector
    steps:
      - name: auth
        description: Authenticate with Proxmox
        task:
          type: model_method
          modelIdOrName: keebDev02
          methodName: auth
        dependsOn: []
        weight: 0
      - name: lookup-vm
        description: Lookup target VM in fleet
        task:
          type: model_method
          modelIdOrName: fleet
          methodName: lookup
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: auth
            condition:
              type: succeeded
        weight: 0
      - name: enable-textfile
        description: Enable node-exporter textfile collector on the VM
        task:
          type: model_method
          modelIdOrName: monitoringAgent
          methodName: enableTextfileCollector
          inputs:
            vmName: '${{ inputs.vmName }}'
        dependsOn:
          - step: lookup-vm
            condition:
              type: succeeded
        weight: 0
    dependsOn: []
    weight: 0
version: 1
